### ISSUE TITLE
Not support nbconvert

### ISSUE THREAD

**Issue by yihengli** [napjon/krisk#62]
**Reproduce:**
1. Use Intro.ipynb
2. Remove `from krisk import init_notebook; init_notebook()` since it's not gonna publish to nbviewer.
3. Use nbconvert to export current page as html

**Output:**
Javascript part failed to print out. 
Console error: 
`require.min.js:8 Uncaught Error: Script error for: dark`
`require.min.js:8 Failed to load resource: net::ERR_FILE_NOT_FOUND`
...

**Expected Output:**
Charts should be shown as it run in notebook after exporting.

**Possible solution:**
It seems like after exporting, it still tries to retrieve source js files from local server and current folder. Is that possible we can define the source files' location as commands in python?

**ENV:**
Python3.5
Jupyter Notebook 4.2.1
Echarts 3.2.1 (built-in)

**Comment by napjon** [comment]
@yihengli : Thank you for reporting this. You should use `init_notebook` when doing nbconvert. nbviewer doing exactly this, which is nbconvert and render the html in the page. nbextension allows you to inject js in the nb environtment. But when producing html, you still should output js. I should fixed my wording in the notebook.

This is still a bug though. It's rather tied to js libraries didn't correctly get called. It used file protocol instead of actually get from online sources.

`file://cdn.rawgit.com/napjon/krisk/master/krisk/static/dark.js Failed to load resource: net::ERR_FILE_NOT_FOUND`

**Comment by napjon** [comment]
Fixed at master
